"""Write Argus onboarding files into ``products/<id>/`` after sync."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from argus.importer.classification import (
    ProductShapeResult,
    shape_dependency_description,
    shape_signals_yaml_preamble,
)
from argus.importer.discover import RepoFacts, display_name_from_facts


def _dump_yaml(data: dict[str, Any]) -> str:
    return yaml.safe_dump(
        data,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
    )


def write_placeholder_scripts(product_root: Path, product_id: str) -> None:
    scripts = product_root / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    for name, body in (
        (
            "start.sh",
            f'#!/usr/bin/env bash\nset -euo pipefail\necho "[{product_id}] Argus placeholder start — wire to real app entrypoint per README."\n',
        ),
        (
            "stop.sh",
            f'#!/usr/bin/env bash\nset -euo pipefail\necho "[{product_id}] Argus placeholder stop"\n',
        ),
        (
            "analyze.sh",
            f'#!/usr/bin/env bash\nset -euo pipefail\necho "[{product_id}] Argus placeholder analyze"\n',
        ),
    ):
        p = scripts / name
        p.write_text(body, encoding="utf-8")
        p.chmod(p.stat().st_mode | 0o111)


def _signal_types_for_facts(facts: RepoFacts) -> list[dict[str, object]]:
    """Enable a conservative default set; temporal is useful for trading-style trees."""
    base = [
        ("filesystem", True),
        ("metrics", True),
        ("health", True),
        ("analytics", True),
        ("cost", True),
        ("execution", True),
    ]
    if facts.is_python_project or not facts.has_package_json:
        base.append(("temporal", True))
    return [{"type": t, "enabled": en} for t, en in base]


def build_product_yaml(
    facts: RepoFacts,
    *,
    operator_team: str,
    operator_name: str,
    product_type: str,
    import_state: dict[str, Any] | None = None,
    shape: ProductShapeResult | None = None,
) -> dict[str, Any]:
    name = display_name_from_facts(facts, facts.product_id)
    metrics_paths: list[str] = []
    if (facts.repo_root / "metrics").is_dir():
        metrics_paths.append("metrics/")
    if (facts.repo_root / "data").is_dir():
        metrics_paths.append("data/")
    if not metrics_paths:
        metrics_paths = []

    onboarding: dict[str, Any] = {
        "version": 1,
        "source_repo_url": facts.github_url,
        "description": (
            facts.project_description
            or (facts.readme_first_line[:240] if facts.readme_first_line else "")
            or "Imported product — see README in-tree for authoritative description."
        ),
        "repo_path": f"products/{facts.product_id}",
        "tech_stack": {
            "languages": _infer_languages(facts),
            "python_requires": facts.requires_python or None,
            "package_manager": facts.package_manager or None,
        },
        "entry_points": facts.script_entries[:12],
        "has_tests": facts.test_path is not None,
        "has_docs": facts.doc_path is not None,
        "security_present": facts.has_security_md,
        "notes": [
            "Generated by Argus importer — review before treating as product truth.",
            "actions.* point to Argus placeholder scripts under ./scripts/ unless overridden.",
            "observed_js_static_paths / tech_hints_grounded list files only — not proof of runtime or production behavior.",
        ],
    }
    if shape is not None:
        onboarding["product_shape"] = shape.to_onboarding_dict()
    if facts.grounded_js_static_paths:
        onboarding["observed_js_static_paths"] = facts.grounded_js_static_paths[:48]
    if facts.tech_hints:
        onboarding["tech_hints_grounded"] = facts.tech_hints[:24]

    raw_ext: dict[str, Any] = {"argus_onboarding": onboarding}
    if import_state is not None:
        raw_ext["import_state"] = import_state

    return {
        "id": facts.product_id,
        "name": name,
        "type": product_type,
        "status": "experimental",
        "state": "validate",
        "owner": {"team": operator_team, "operator": operator_name},
        "metrics": {"local_paths": metrics_paths, "primary": []},
        "cost": {"monthly_usd": 0, "notes": "Not estimated at import time — adjust after real cost data."},
        "signals": _signal_types_for_facts(facts),
        "actions": {
            "start": "./scripts/start.sh",
            "stop": "./scripts/stop.sh",
            "analyze": "./scripts/analyze.sh",
        },
        "constraints": {"max_monthly_cost_usd": 10_000, "min_activity_threshold": 0},
        "lifecycle": {"stage": "validate", "next_gate": "First Argus evaluation complete — human gate for roadmap"},
        "raw_extensions": raw_ext,
    }


def _path_to_signal_id(rel: str, *, used: set[str]) -> str:
    """Filesystem-derived manifest id; disambiguates collisions."""
    raw = re.sub(r"[^a-zA-Z0-9]+", "_", rel.replace("/", "_")).strip("_").lower()
    if not raw:
        raw = "file"
    base = f"fs_{raw}"[:52]
    cand = base
    n = 0
    while cand in used:
        n += 1
        cand = f"{base}_{n}"[:56]
    used.add(cand)
    return cand


def _infer_languages(facts: RepoFacts) -> list[str]:
    langs: list[str] = []
    if facts.is_python_project:
        langs.append("Python")
    if facts.has_package_json:
        langs.append("JavaScript")
    if not langs:
        langs.append("unknown")
    return langs


def build_signals_yaml_entries(
    facts: RepoFacts,
    *,
    shape: ProductShapeResult | None = None,
) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    dep_desc_py = "Project manifest / dependencies (pyproject.toml)"
    dep_desc_js = "Package manifest (package.json)"
    if shape is not None:
        tuned = shape_dependency_description(facts, shape)
        dep_desc_py = tuned if (facts.repo_root / "pyproject.toml").is_file() else dep_desc_py
        dep_desc_js = tuned if (facts.repo_root / "package.json").is_file() else dep_desc_js
    if (facts.repo_root / "pyproject.toml").is_file():
        entries.append(
            {
                "id": "dependency_health",
                "category": "quality",
                "source_type": "filesystem",
                "path": "pyproject.toml",
                "freshness_sla": "7d",
                "value_type": "string",
                "required_for": "none",
                "trust_level": "heuristic",
                "description": dep_desc_py,
            }
        )
    elif (facts.repo_root / "package.json").is_file():
        entries.append(
            {
                "id": "dependency_health",
                "category": "quality",
                "source_type": "filesystem",
                "path": "package.json",
                "freshness_sla": "7d",
                "value_type": "string",
                "required_for": "none",
                "trust_level": "heuristic",
                "description": dep_desc_js,
            }
        )

    if facts.test_path:
        entries.append(
            {
                "id": "test_health",
                "category": "quality",
                "source_type": "filesystem",
                "path": facts.test_path,
                "freshness_sla": "14d",
                "value_type": "string",
                "required_for": "none",
                "trust_level": "heuristic",
                "description": "Representative test file present (heuristic pick)",
            }
        )

    if facts.doc_path:
        entries.append(
            {
                "id": "documentation",
                "category": "experience",
                "source_type": "filesystem",
                "path": facts.doc_path,
                "freshness_sla": "30d",
                "value_type": "string",
                "required_for": "none",
                "trust_level": "heuristic",
                "description": "Documentation anchor (first match under docs/ or README-linked)",
            }
        )

    if facts.has_security_md:
        entries.append(
            {
                "id": "security",
                "category": "compliance",
                "source_type": "filesystem",
                "path": "SECURITY.md",
                "freshness_sla": "90d",
                "value_type": "string",
                "required_for": "none",
                "trust_level": "authoritative",
                "description": "Security policy file present",
            }
        )

    seen_paths = {str(e.get("path")) for e in entries if e.get("path")}
    used_ids = {str(e.get("id")) for e in entries if e.get("id")}
    js_added = 0
    for rel in facts.grounded_js_static_paths:
        if js_added >= 8:
            break
        if rel.endswith("/"):
            continue
        if rel in seen_paths:
            continue
        # Skip package.json if already covered by dependency_health
        if rel == "package.json" and any(e.get("id") == "dependency_health" for e in entries):
            continue
        slug = _path_to_signal_id(rel, used=used_ids)
        entries.append(
            {
                "id": slug,
                "category": "operational",
                "source_type": "filesystem",
                "path": rel,
                "freshness_sla": "30d",
                "value_type": "string",
                "required_for": "none",
                "trust_level": "heuristic",
                "description": f"Observed config or entry file (path only — not a behavioral claim): {rel}",
            }
        )
        seen_paths.add(rel)
        js_added += 1

    if not entries:
        readme_names = ("README.md", "readme.md", "Readme.md")
        for rn in readme_names:
            if (facts.repo_root / rn).is_file():
                entries.append(
                    {
                        "id": "repo_readme",
                        "category": "experience",
                        "source_type": "filesystem",
                        "path": rn,
                        "freshness_sla": "30d",
                        "value_type": "string",
                        "required_for": "none",
                        "trust_level": "heuristic",
                        "description": "Fallback anchor — README (expand manifest after review)",
                    }
                )
                break
        else:
            mds = sorted(facts.repo_root.glob("*.md"))
            if mds:
                p = mds[0].relative_to(facts.repo_root).as_posix()
                entries.append(
                    {
                        "id": "markdown_anchor",
                        "category": "experience",
                        "source_type": "filesystem",
                        "path": p,
                        "freshness_sla": "30d",
                        "value_type": "string",
                        "required_for": "none",
                        "trust_level": "heuristic",
                        "description": "First markdown file at repo root (heuristic fallback)",
                    }
                )
            elif (facts.repo_root / "index.html").is_file():
                entries.append(
                    {
                        "id": "site_entry_html",
                        "category": "experience",
                        "source_type": "filesystem",
                        "path": "index.html",
                        "freshness_sla": "30d",
                        "value_type": "string",
                        "required_for": "none",
                        "trust_level": "heuristic",
                        "description": "Static site entry (index.html) — minimal filesystem anchor",
                    }
                )

    return entries


def write_signals_yaml(
    product_root: Path,
    facts: RepoFacts,
    *,
    shape: ProductShapeResult | None = None,
) -> None:
    payload = {
        "schema": "argus.product_signal_manifest.v1",
        "product_id": facts.product_id,
        "signals": build_signals_yaml_entries(facts, shape=shape),
    }
    head = (
        "# Product-owned signal declarations (argus.product_signal_manifest.v1).\n"
        "# Paths are repo-relative to this product directory.\n"
    )
    if shape is not None:
        head += shape_signals_yaml_preamble(shape) + "\n"
    head += "\n"
    (product_root / "signals.yaml").write_text(head + _dump_yaml(payload), encoding="utf-8")


def write_product_yaml_file(product_root: Path, data: dict[str, Any]) -> None:
    (product_root / "product.yaml").write_text(_dump_yaml(data), encoding="utf-8")


def write_minimal_doctrine(product_root: Path, facts: RepoFacts, max_cost: float) -> None:
    """Only non-speculative policy: mirror cost cap; summary explicitly not inferred."""
    doc = {
        "schema": "argus.doctrine.v1",
        "summary": "Imported product — principles not inferred by tooling; see README and import_notes.md.",
        "principles": [
            "Prefer explicit operator review before irreversible actions.",
        ],
        "constraints": {"max_monthly_cost_usd": max_cost, "require_human_review_when_kill_candidate": True},
        "scoring": {},
    }
    (product_root / "doctrine.yaml").write_text(_dump_yaml(doc), encoding="utf-8")


def write_import_notes(
    product_root: Path,
    facts: RepoFacts,
    *,
    excludes: list[str],
    assumptions: list[str],
    uncertainties: list[str],
    weak_areas: list[str],
    domain_signal_hints: list[str],
    static_site_notes: str,
    product_shape: ProductShapeResult | None = None,
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# {facts.product_id} — Argus import notes (tool-generated)",
        "",
        f"Generated (UTC): {now}",
        f"Source URL: {facts.github_url}",
        "",
        "## A. Importer version",
        "",
        "- Tool: `argus.importer` v1",
        "- Primary input: GitHub HTTPS URL (not a local path).",
        "- Durable machine state: `raw_extensions.import_state` in `product.yaml` (not a substitute for README).",
        "- Inspect without re-import: `python tools/import_product.py status --product-id <id>` (or `--product-id <id> --status`).",
        "",
        "## B. Exclusions applied (sync from clone → product tree)",
        "",
        "Patterns excluded from the copy (see stdout summary for the exact list used on this run):",
        "",
    ]
    for p in excludes:
        lines.append(f"- `{p}`")
    lines.extend(
        [
            "",
            "### Policy notes",
            "",
            "- **`.cursor/`** excluded by default (IDE metadata). Use `--include-cursor` to copy.",
            "- **Local DB files** (`*.db`, `*.sqlite*`) excluded by default. Use `--include-local-db-artifacts` if the product needs them under `products/<id>/`.",
            "- **`node_modules/`** excluded when `--exclude-node-artifacts` is set (default: on for static/JS-heavy prep).",
            "",
        ]
    )
    if product_shape is not None:
        lines.extend(
            [
                "## C.0 Evidence-backed product shape (heuristic)",
                "",
                product_shape.hedged_summary,
                "",
                "Supporting observations (files only — not runtime behavior):",
                "",
            ]
        )
        for ev in product_shape.evidence:
            lines.append(f"- {ev}")
        lines.extend(
            [
                "",
                product_shape.to_onboarding_dict().get("disclaimer", ""),
                "",
            ]
        )
    lines.extend(
        [
            "## C. Grounded facts from repo scan",
            "",
        ]
    )
    for s in facts.summary_lines():
        lines.append(f"- {s}")
    lines.append("")
    lines.append("## D. Assumptions (explicit)")
    for a in assumptions:
        lines.append(f"- {a}")
    lines.extend(["", "## E. Uncertainties / human follow-ups"])
    for u in uncertainties:
        lines.append(f"- {u}")
    lines.extend(["", "## F. Likely weak areas (import)"])
    for w in weak_areas:
        lines.append(f"- {w}")
    lines.extend(["", "## G. Domain-specific signal opportunities (ideas only)"])
    for d in domain_signal_hints:
        lines.append(f"- {d}")
    lines.extend(
        [
            "",
            "## H. Iterative improvement loop (developer workflow)",
            "",
            "After each import run:",
            "",
            "1. Read this file and `first_pass_argus_summary.md`.",
            "2. Note what the importer got **right** vs **wrong** (section I below).",
            "3. Adjust heuristics in `argus/importer/` or flags; re-run from the same `--repo-url`.",
            "4. Compare signal/findings/ideas noise versus the prior run.",
            "",
            "### I. What went well / wrong (fill on review)",
            "",
            "| Area | Good | Bad | Rule change for next repo |",
            "|------|------|-----|---------------------------|",
            "| Excludes | | | |",
            "| Manifest paths | | | |",
            "| product.yaml typing | | | |",
            "| Doctrine | | | |",
            "",
            "## J. Static-site / non-Python repos (future)",
            "",
            static_site_notes,
            "",
        ]
    )
    (product_root / "import_notes.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
